---
title: "pro1"
author: "Nannan Wang"
date: "September 17, 2018"
output: html_document
---
```{r}
library(tidyverse)
library(tidytext)
library(DT)
library(scales)
library(wordcloud2)
library(gridExtra)
library(ngram)
library(shiny)
library(dplyr)
library(ggplot2)
```
# Data Cleaning
```{r}
urlfile1 <- 'https://raw.githubusercontent.com/rit-public/HappyDB/master/happydb/data/cleaned_hm.csv'
hm_data <- read_csv(urlfile1)
urlfile2 <- 'https://raw.githubusercontent.com/rit-public/HappyDB/master/happydb/data/demographic.csv'
demographic <- read_csv(urlfile2)
fulldata <- full_join(hm_data, demographic, c("wid" = "wid"))
new <- fulldata[,-1]
newdata <- new %>%
  filter(gender %in% c("m", "f")) %>%
  filter(marital %in% c("single", "married")) %>%
  filter(parenthood %in% c("n", "y")) %>%
  filter(reflection_period %in% c("24h", "3m")) %>%
  mutate(reflection_period = fct_recode(reflection_period, 
                                        months_3 = "3m", hours_24 = "24h"))
newdata <- na.omit(newdata)
# head(newdata)
```

# Word Count
```{r}
ggplot(newnewdata, aes(x=word.count)) +
  xlim(0,100) +
  geom_histogram(bins=30, aes(fill = ..count..)) + 
  geom_vline(aes(xintercept=mean(word.count)),
             color="#FFFFFF", linetype="dashed", size=1) +
  geom_density(aes(y=4 * ..count..),alpha=.2, fill="#1CCCC6") +
  ylab("num of moments") + xlab ("word.numbers") +
  ggtitle("Distribution of word count") +
  theme_minimal()
```

# Word Frequency
```{r}
# wordcloud2( , size = 1,color = 'random-light',
     #backgroundColor = "gray", fontWeight='bold',fontFamily = "Ink Free",
     #minRotation = -pi/3, maxRotation = pi/3,rotateRatio = 0.8)
```

# Percentage of Happy Moments by Category
```{r}
ggplot(data.frame(prop.table(table(newdata$predicted_category))), aes(x=Var1, y = Freq*100, fill = Var1)) + 
  geom_bar(stat = 'identity') + 
  xlab('Happy Category') + 
  ylab('Percentage of Happy Moments (%)') + 
  geom_text(aes(label=round(Freq*100,2)), vjust=-0.25) + 
  ggtitle('Percentage of Happy Moments by Category')
```

# Happy Category by Age
```{r}
newdata$age <- as.numeric(as.character(newdata$age))
ages <- newdata  %>% select(wid, age, predicted_category) %>% mutate(Age_group = ifelse(age < 18, '0-18',ifelse(age < 30, '18-29', ifelse(age < 40, '30-39', ifelse(age < 50, '40-49', ifelse(age < 60, '50-59', ifelse(age < 70, '60-69', ifelse(age < 80, '70-79', ifelse(age < 90, '80-89', '90-99')))))))))

ages <- ages %>% mutate(Age_group = factor(Age_group), predicted_category = factor(predicted_category, levels = rev(c( 'achievement', 'affection', 'bonding',  'enjoy_the_moment','exercise', 'leisure', 'nature'))))

ages %>% filter(age < 100) %>% group_by(Age_group) %>% count(predicted_category) %>% ggplot(aes(predicted_category, n, fill = Age_group)) + geom_bar(stat='identity', show.legend = FALSE) + facet_wrap(~Age_group, scales = 'free') + xlab('Happy Category') + ylab('Number of Happy Moments') + geom_text(aes(label = n), hjust = .73) + coord_flip()
```












